version: 2.0
jobs:
  build:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Updating Packages
          command: 'apt-get update'
      - run:
          name: Installing CMAKE
          command: 'apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -S. -Bbuild -DDEVOPT_EXCLUDE_PRETEST_FROM_ALL=On'
      - run:
          name: Building ALL
          command: 'cmake --build build -j 4'
  test:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Updating Packages
          command: 'apt-get update'
      - run:
          name: Installing CMAKE
          command: 'apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DDEVOPT_ENABLE_COVERAGE_REPORT=On'
      - run:
          name: Building Pretest
          command: 'cmake --build build --target pretest -j 2'
      - run:
          name: Running Tests
          command: 'ctest -j 2'
      - run:
          name: Uploading Code Coverage
          command: 'cmake --build build --target upload_codecov'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build