name: "Test"
on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          setup-options: -Db_coverage=true
