name: "Test"
on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install Boost
        run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev
      - name: Install Eigen
        run: sudo apt-get update && sudo apt-get install -yq libeigen3-dev
      - name: Install HTSLib
        run: sudo apt-get update && sudo apt-get install -yq libhts-dev
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          setup-options: -Db_coverage=true
          meson-version: 0.59.1
          ninja-version: 1.10.2

